/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.vut.ifje.project;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.stream.Collectors;

public class App {
    public static String usage(String name) {
        return "Usage: " + name + " [input-file] [-o output-file]";
    }

    public static void main(String[] args) {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        System.out.print(reader.lines().collect(Collectors.joining("\n")));
    }
}
