package org.vut.ifje.project.reporter.error;

import org.vut.ifje.project.reporter.Cursor;

/**
 * A lexical error represents an error occurred when a malformed token is found.
 * These are usually generated by the <code>Scanner</code>.
 */
public class LexicalError extends Error {
    /**
     * Constructs and initializes a lexical error with an explanation and a cursor.
     *
     * @param explanation the explanation of the newly constructed error
     * @param cursor      the cursor that points to the beginning of the cursor that generated the error
     */
    public LexicalError(String explanation, Cursor cursor) {
        super(explanation, cursor);
    }

    @Override
    public String print() {
        return "Lexical error at " + cursor + ": " + explanation;
    }
}
