package org.vut.ifje.project.reporter.error;

import org.vut.ifje.project.reporter.Cursor;

/**
 * A syntax error represents an error related to bad syntax.
 * These are usually generated by the <code>Parser</code>.
 */
public class SyntaxError extends Error {
    private String hint = null;

    /**
     * Constructs and initializes a syntax error with an explanation and a cursor.
     *
     * @param explanation the explanation of the newly constructed error
     * @param cursor      the cursor that points to the beginning of the token that generated the error
     */
    public SyntaxError(String explanation, Cursor cursor) {
        super(explanation, cursor);
    }

    /**
     * Construct and initializes a syntax error with an explanation, a hint and a cursor.
     *
     * @param explanation the explanation of the newly constructed error
     * @param hint        the hint to get rid of this error
     * @param cursor      the cursor that points to the beginning of the token that generated the error
     */
    public SyntaxError(String explanation, String hint, Cursor cursor) {
        super(explanation, cursor);
        this.hint = hint;
    }

    @Override
    public String print() {
        StringBuilder description = new StringBuilder().append("Syntax error at ")
                .append(cursor)
                .append(": ")
                .append(explanation);

        if (hint != null) {
            description.append("\n\thelp: ")
                    .append(hint);
        }

        return description.toString();
    }
}
